FROM mageai/mageai:latest

# Instalar dependencias del pipeline geoespacial
RUN pip install --no-cache-dir \
    geopandas==0.14.4 \
    shapely==2.0.2 \
    requests==2.31.0 \
    pandas==2.2.0 \
    sqlalchemy==2.0.27 \
    psycopg2-binary==2.9.9