FROM mageai/mageai:0.9.79

# Mage ya incluye Pandas, SQLAlchemy, requests y psycopg2 en versiones compatibles.
RUN pip install --no-cache-dir \
    geopandas==0.14.4 \
    shapely==2.0.2 \
    kafka-python==2.3.0
